<?php

namespace Ecommerce\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
public function findSousCategorie()
    {
        $qb = $this
    ->createQueryBuilder('c')

  ;

  return $qb
    ->getQuery()
    ->getResult()
  ;
    }


}
